{{- if and .Values.postgresql.enabled .Values.secrets.postgresql.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wander.fullname" . }}-postgresql-secret
  labels:
    {{- include "wander.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  password: {{ .Values.secrets.postgresql.password | quote }}
{{- end }}
