{{- if and .Values.redis.enabled .Values.secrets.redis.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wander.fullname" . }}-redis-secret
  labels:
    {{- include "wander.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
type: Opaque
stringData:
  redis-password: {{ .Values.secrets.redis.password | quote }}
{{- end }}
